minimum-gas-prices = "0.025tics"
pruning = "custom"
pruning-keep-recent = "2000"
pruning-keep-every = "0"
pruning-interval = "50"
halt-height = 0
halt-time = 0
min-retain-blocks = 0
inter-block-cache = true
index-events = "[]"
iavl-cache-size = 781250
iavl-disable-fastnode = false
iavl-lazy-loading = false
app-db-backend = ""
indexer = "null"
snapshot-interval = 0
snapshot-keep-recent = 2

[telemetry]
service-name = ""
enabled = false
enable-hostname = false
enable-hostname-label = false
enable-service-label = false
prometheus-retention-time = 0
global-labels = "[]"

[api]
enable = false
swagger = false
address = "tcp://0.0.0.0:1317"
max-open-connections = 1000
rpc-read-timeout = 10
rpc-write-timeout = 0
rpc-max-body-bytes = 1000000
enabled-unsafe-cors = true

[rosetta]
enable = false
address = ":8080"
blockchain = "app"
network = "network"
retries = 3
offline = false
enable-fee-suggestion = false
gas-to-suggest = 200000
denom-to-suggest = "uatom"

[grpc]
enable = true
address = "0.0.0.0:9090"
max-recv-msg-size = "10485760"
max-send-msg-size = "2147483647"

[grpc-web]
enable = false
address = "0.0.0.0:9091"
enable-unsafe-cors = true

[state-sync]
snapshot-interval = 0
snapshot-keep-recent = 0

[store]
streamers = []

[streamers]
[streamers.file]
keys = ["*", ]
write_dir = ""
prefix = ""
output-metadata = "true"
stop-node-on-error = "true"
fsync = "false"

[mempool]
max-txs = 2000
version = "v0"
size = 10000
max_txs_bytes = 536870912
cache_size = 16000
ttl-num = 0
ttl-duration = "0s"

[evm]
tracer = ""
max-tx-gas-wanted = 0

[json-rpc]
enable = false
address = "0.0.0.0:8545"
ws-address = "0.0.0.0:8546"
api = "eth,net,web3"
gas-cap = 25000000
allow-insecure-unlock = false
evm-timeout = "5s"
txfee-cap = 1
filter-cap = 200
feehistory-cap = 100
logs-cap = 10000
block-range-cap = 10000
http-timeout = "30s"
http-idle-timeout = "2m0s"
allow-unprotected-txs = false
max-open-connections = 0
enable-indexer = false
metrics-address = "0.0.0.0:6065"
fix-revert-gas-refund-height = 0

[tls]
certificate-path = ""
key-path = ""

[memiavl]
enable = false
zero-copy = false
async-commit-buffer = 0
snapshot-keep-recent = 0
snapshot-interval = 0
cache-size = 1000
