proxy_app = "tcp://0.0.0.0:26658"
moniker = "bannon-validator-x8"
block_sync = true
db_backend = "goleveldb"
db_dir = "data"
log_level = "info"
log_format = "plain"
genesis_file = "config/genesis.json"
priv_validator_key_file = "config/priv_validator_key.json"
priv_validator_state_file = "data/priv_validator_state.json"
priv_validator_laddr = ""
node_key_file = "config/node_key.json"
abci = "socket"
filter_peers = false

[rpc]
laddr = "tcp://127.0.0.1:26657"
cors_allowed_origins = "['*']"
cors_allowed_methods = "['HEAD', 'GET', 'POST']"
cors_allowed_headers = "['Origin', 'Accept', 'Content-Type', 'X-Requested-With', 'X-Server-Time']"
grpc_laddr = ""
grpc_max_open_connections = 900
unsafe = false
max_open_connections = 1024
max_subscription_clients = 100
max_subscriptions_per_client = 5
experimental_subscription_buffer_size = 200
experimental_websocket_write_buffer_size = 600
experimental_close_on_slow_client = true
timeout_broadcast_tx_commit = "10s"
max_body_bytes = 1000000
max_header_bytes = 1048576
tls_cert_file = ""
tls_key_file = ""
pprof_laddr = "127.0.0.1:6060"

[p2p]
laddr = "tcp://0.0.0.0:26656"
external_address = "tcp://73.3.165.55:26656"
seeds = ""
persistent_peers = "65cb0de46806c3e50395110b84d22275a29150ca@38.242.244.114:26656,f874aca4075ce71b7e0fa62f882d7bb69aed9adc@85.195.254.66:26656,41f8e8b5479374a21e69be09911a0c0dc6f41b23@49.0.247.123:26656,ad8e2053470a347d87f5125d54fe04d86155f7c4@159.138.134.250:26656"
addr_book_file = "config/addrbook.json"
addr_book_strict = false
max_num_inbound_peers = 24
max_num_outbound_peers = 12
unconditional_peer_ids = "65cb0de46806c3e50395110b84d22275a29150ca,f874aca4075ce71b7e0fa62f882d7bb69aed9adc"
persistent_peers_max_dial_period = "20s"
flush_throttle_timeout = "25ms"
max_packet_msg_payload_size = 1024
send_rate = 10485760
recv_rate = 10485760
pex = true
seed_mode = false
private_peer_ids = ""
allow_duplicate_ip = true
handshake_timeout = "10s"
dial_timeout = "3s"
max_num_peers = 36
peer_gossip_sleep_duration = "80ms"
peer_query_maj23_sleep_duration = "1.5s"

[mempool]
version = "v0"
type = "flood"
recheck = false
broadcast = true
wal_dir = ""
size = 2000
max_txs_bytes = 268435456
cache_size = 50000
keep-invalid-txs-in-cache = false
max_tx_bytes = 524288
max_batch_bytes = 0
ttl-duration = "0s"
ttl-num-blocks = 0
experimental_max_gossip_connections_to_persistent_peers = 6
experimental_max_gossip_connections_to_non_persistent_peers = 10

[statesync]
enable = false
rpc_servers = ""
trust_height = 0
trust_hash = ""
trust_period = "112h0m0s"
discovery_time = "15s"
temp_dir = ""
chunk_request_timeout = "10s"
chunk_fetchers = "4"

[blocksync]
version = "v0"

[consensus]
wal_file = "data/cs.wal/wal"
timeout_propose = "2s"
timeout_propose_delta = "300ms"
timeout_prevote = "1s"
timeout_prevote_delta = "300ms"
timeout_precommit = "1s"
timeout_precommit_delta = "300ms"
timeout_commit = "6s"
double_sign_check_height = 0
skip_timeout_commit = false
create_empty_blocks = false
create_empty_blocks_interval = "0s"
peer_gossip_sleep_duration = "10ms"
peer_query_maj23_sleep_duration = "2s"

[storage]
discard_abci_responses = true

[tx_index]
indexer = "null"
psql-conn = ""

[instrumentation]
prometheus = true
prometheus_listen_addr = "127.0.0.1:26660"
max_open_connections = 3
namespace = "cometbft"
